<a href="https://colab.research.google.com/github/AlexaMarieDonato/58013-LinearAlgebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. Consider the four matrices, (20 points each)

In [23]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.array([[1, 2], [3, 4]])
#a. AB
print("This is AB")
multiply = np.dot(A, B)
print(multiply)
#b. D + D
print("This is D + D")
add = np.add(D, D)
print(add)
#c. 2C
print("This is 2C")
m = 2*C
print(m)

This is AB
[[22 28]
 [49 64]]
This is D + D
[[2 4]
 [6 8]]
This is 2C
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2. Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8].

In [25]:
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])
product = np.cross(A, B)
print("The cross product of A and B is", product)

#SOLUTION
#A = 2i + 7j + 4k
#B = 3i + 9j + 8k
i = ((A[1]*B[2]) - (A[2]*B[1]))
j = ((A[2]*B[0]) - (A[0]*B[2]))
k = ((A[0]*B[1]) - (A[1]*B[0]))
print("The cross product of A and B is", i, "i", j, "j", k, "k")

The cross product of A and B is [20 -4 -3]
The cross product of A and B is 20 i -4 j -3 k
