<a href="https://colab.research.google.com/github/AlexaMarieDonato/58013-LinearAlgebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prelim Exam

Question 1. (20 points) Create a Multiplication Table/Chart of 1 to 10 using numpy/ python program.

In [6]:
import numpy as np
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for i in numbers:
  print("The multiplication table/chart for", i)
  a = np.multiply(i, numbers[0])
  b = np.multiply(i, numbers[1])
  c = np.multiply(i, numbers[2])
  d = np.multiply(i, numbers[3])
  e = np.multiply(i, numbers[4])
  f = np.multiply(i, numbers[5])
  g = np.multiply(i, numbers[6])
  h = np.multiply(i, numbers[7])
  j = np.multiply(i, numbers[8])
  k = np.multiply(i, numbers[9])
  print(i, "X", numbers[0], "=", a)
  print(i, "X", numbers[1], "=", b)
  print(i, "X", numbers[2], "=", c)
  print(i, "X", numbers[3], "=", d)
  print(i, "X", numbers[4], "=", e)
  print(i, "X", numbers[5], "=", f)
  print(i, "X", numbers[6], "=", g)
  print(i, "X", numbers[7], "=", h)
  print(i, "X", numbers[8], "=", j)
  print(i, "X", numbers[9], "=", k)
  i+=1

The multiplication table/chart for 1
1 X 1 = 1
1 X 2 = 2
1 X 3 = 3
1 X 4 = 4
1 X 5 = 5
1 X 6 = 6
1 X 7 = 7
1 X 8 = 8
1 X 9 = 9
1 X 10 = 10
The multiplication table/chart for 2
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
2 X 10 = 20
The multiplication table/chart for 3
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
3 X 10 = 30
The multiplication table/chart for 4
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36
4 X 10 = 40
The multiplication table/chart for 5
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50
The multiplication table/chart for 6
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54
6 X 10 = 60
The multiplication table/chart for 7
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 

Question 2. (10 points) In relation to Question 1, show a solution that doubles all the values of each element.

In [7]:
import numpy as np
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for i in numbers:
  print("The multiplication table for", i, "with doubled values in each element")
  a = np.multiply(i, numbers[0])
  b = np.multiply(i, numbers[1])
  c = np.multiply(i, numbers[2])
  d = np.multiply(i, numbers[3])
  e = np.multiply(i, numbers[4])
  f = np.multiply(i, numbers[5])
  g = np.multiply(i, numbers[6])
  h = np.multiply(i, numbers[7])
  j = np.multiply(i, numbers[8])
  k = np.multiply(i, numbers[9])
  print(i, "X", numbers[0], "=", 2*a)
  print(i, "X", numbers[1], "=", 2*b)
  print(i, "X", numbers[2], "=", 2*c)
  print(i, "X", numbers[3], "=", 2*d)
  print(i, "X", numbers[4], "=", 2*e)
  print(i, "X", numbers[5], "=", 2*f)
  print(i, "X", numbers[6], "=", 2*g)
  print(i, "X", numbers[7], "=", 2*h)
  print(i, "X", numbers[8], "=", 2*j)
  print(i, "X", numbers[9], "=", 2*k)
  i+=1

The multiplication table for 1 with doubled values in each element
1 X 1 = 2
1 X 2 = 4
1 X 3 = 6
1 X 4 = 8
1 X 5 = 10
1 X 6 = 12
1 X 7 = 14
1 X 8 = 16
1 X 9 = 18
1 X 10 = 20
The multiplication table for 2 with doubled values in each element
2 X 1 = 4
2 X 2 = 8
2 X 3 = 12
2 X 4 = 16
2 X 5 = 20
2 X 6 = 24
2 X 7 = 28
2 X 8 = 32
2 X 9 = 36
2 X 10 = 40
The multiplication table for 3 with doubled values in each element
3 X 1 = 6
3 X 2 = 12
3 X 3 = 18
3 X 4 = 24
3 X 5 = 30
3 X 6 = 36
3 X 7 = 42
3 X 8 = 48
3 X 9 = 54
3 X 10 = 60
The multiplication table for 4 with doubled values in each element
4 X 1 = 8
4 X 2 = 16
4 X 3 = 24
4 X 4 = 32
4 X 5 = 40
4 X 6 = 48
4 X 7 = 56
4 X 8 = 64
4 X 9 = 72
4 X 10 = 80
The multiplication table for 5 with doubled values in each element
5 X 1 = 10
5 X 2 = 20
5 X 3 = 30
5 X 4 = 40
5 X 5 = 50
5 X 6 = 60
5 X 7 = 70
5 X 8 = 80
5 X 9 = 90
5 X 10 = 100
The multiplication table for 6 with doubled values in each element
6 X 1 = 12
6 X 2 = 24
6 X 3 = 36
6 X 4 = 48
6 X 5 

Question 3. (10 points) Create a square matrix that has a diagonal 1's.

In [1]:
import numpy as np
square = np.eye(4,4)
print(square)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 4. (30 points) Create a matrix whose elements are the given:

In [4]:
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
#Type a python program that can view the size, shape, and dimension of the matrix above.
size = np.size(matrix)
print(size)
shape = np.shape(matrix)
print(shape)
dim = matrix.ndim
print(dim)

12
(3, 4)
2


Question 5. (30 points) Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element.

In [2]:
import numpy as np
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 18, 27]])
add = np.add(arrayOne, arrayTwo)
print(add)
print(add*add)

[[20 39 33]
 [25 36 54]]
[[ 400 1521 1089]
 [ 625 1296 2916]]
