<a href="https://colab.research.google.com/github/AlexaMarieDonato/58013-LinearAlgebra/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Operations

Vector Addition

In [4]:
import numpy as np
A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])
print(A+B+C)
D = np.add(A,np.add(B,C))
E = np.sum(B)
print(D)
print(E)

[ 4  3 -1]
[ 4  3 -1]
2


Vector Subtraction

In [7]:
F = np.subtract(A,B)
print(A-B)
print(F)

[-2  1  2]
[-2  1  2]


Vector Multiplication

In [8]:
G = np.multiply(A,B)
print(A*B)
print(G)

[3 2 0]
[3 2 0]


Vector Division

In [10]:
H = np.divide(A,B)
print(A/B)
print(H)

I = np.array([3.9,1.8,7.7])
J = np.array([1,1,1])
print(I//J)
print(np.array(A/B,dtype=int))

[ 0.33333333  2.         -0.        ]
[ 0.33333333  2.         -0.        ]
[3. 1. 7.]
[0 2 0]
