<a href="https://colab.research.google.com/github/AlexaMarieDonato/58013-LinearAlgebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

System of Linear Equation

In [ ]:
import numpy as np
X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


Coding Activity 10

In [9]:
#So let's start off with an easy one. Let's say you have a bakery and you are purchasing supplies consisting of flour, yeast, and eggs from your supplier.
#For month 1 you bought a bakery promo that consists of 30 sacks of flour, 10 packs of yeast, and 120 eggs and you are charged for 12,500 pesos.
#For month two you bought a different bakery promo that consists of 40 sacks of flour, 20 packs of yeast, and 200 eggs then you are charged with 18,000 pesos.
#And then for month three you bought yet a different bakery promo that consists of 50 sacks of flour, 40 packs of yeast, and 360 eggs for 25,700 pesos.
#Now you are wondering if the promos are more cost-effective compared to buying them as a regular buyer, what could be the price of the flour per sack, yeast per pack, and one piece of egg?
#Create a python program to solve for the price of flour per sack, yeast per pack, and one piece of egg.
import numpy as np

eq1 = 30*x + 10*y + 120*z == 12500
eq2 = 40*x + 20*y + 200*z == 18000
eq3 = 50*x + 40*y + 360*z == 25700

A = np.array([[30, 10, 120], [40, 20, 200], [50, 40, 360]])
A1 = np.array([[12500, 10, 120], [18000, 20, 200], [25700, 40, 360]])
A2 = np.array([[30, 12500, 120], [40, 18000, 200], [50, 25700, 360]])
A3 = np.array([[30, 10, 12500], [40, 20, 18000], [50, 40, 25700]])
dA = np.linalg.det(A)
dA1 = np.linalg.det(A1)
dA2 = np.linalg.det(A2)
dA3 = np.linalg.det(A3)
x = dA1/dA
y = dA2/dA
z = dA3/dA
print("As computed using the previous bakery promos, the price of flour per sack is:", x, "pesos")
print("The price of yeast per pack is:", y, "pesos")
print("And the price for one piece of egg is:", z, "pesos")

As computed using the previous bakery promos, the price of flour per sack is: 329.99999999999784 pesos
The price of yeast per pack is: 139.99999999999994 pesos
And the price for one piece of egg is: 10.000000000000242 pesos
