<a href="https://colab.research.google.com/github/AlexaMarieDonato/58013-LinearAlgebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix Algebra

In [21]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
A = np.array([[1,4],[0,3]])
np.linalg.det(A)

3.0000000000000004

In [22]:
B = np.array([[1,3,5,6],[0,3,1,3],[3,1,8,2],[5,2,6,8]])
np.linalg.det(B)

-235.0000000000002

Coding Activity 9

In [23]:
#Prove and implement the remaining 6 matrix multiplication properties.
#You may create your own matrices in which their shapes should not be lower than (3,3).
#In your methodology, create individual flowcharts for each property and discuss
#the property you would then present your proofs or validity of your implementation
#in the results section by comparing your result to present functions from NumPy.

import numpy as np
#Associative Property
A = np.array([
[5,9,4,1],
[2,4,6,8],
[1,3,5,7],
[7,8,10,5]])
B = np.array([
[6,1,2,5],
[2,9,10,4],
[6,9,8,5],
[3,8,10,4]])
C = np.array([
[5,2,1,7],
[9,4,3,8],
[4,6,5,10],
[1,8,7,5]])
print((A*B)*C)
print(A*(B*C))
print("This shows Associative property, where A*(B*C) = (A*B)*C.")
print("----------------------------------------------------------")
#Commutative Property
C = np.array([
[5,9,4,1],
[2,4,6,8],
[1,3,5,7],
[7,8,10,5]])
D = np.array([
[5,2,1,7],
[9,4,3,8],
[4,6,5,10],
[1,8,7,5]])
print(np.dot(C,D))
print(np.dot(D,C))
print("This shows Commutative property, where C*D is shown to be not equal to D*C.")
print("----------------------------------------------------------")
#Distributive Property
print(A*(B+C))
print((A*B)+(A*C))
print("This shows Distributive property, where we can see that A*(B + C) = (A*B) + (A*C).")
print("----------------------------------------------------------")
#Multiplication of Zero Property
E = np.array([[0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0]])
print("A = ", A)
print("E = ", E)
print("E multiplied to A is:")
print(E*A)
print("This shows Multiplication of zero property, where all values will be zero when any matrix is multiplied to a matrix that only has zeros.")
print("----------------------------------------------------------")
#Dimension Property
D = np.array([
[5,2],
[9,4],
[4,6],
[1,8]])
C = np.array([
[5,9,4,1],
[2,4,6,8]])
print("D = ", D)
print("C = ", C)
print("D multiplied to C is: ")
print(np.dot(D,C))
print("This shows Dimension property, where since the dimensions of the two matrices are 4 by 2 and 2 by 4, the dimensions of the product is 4 by 4,")
print("since it will take the outer values of the dimensions of the matrices, which in this case, are 4 and 4.")
print("----------------------------------------------------------")
#Multiplicative Property
E = np.array([
[1,0,0,0],
[0,1,0,0],
[0,0,1,0],
[0,0,0,1]])
B = np.array([
[6,1,2,5],
[2,9,10,4],
[6,9,8,5],
[3,8,10,4]])
print("E = ", E)
print("B = ", B)
print("B multiplied to E is: ")
print(np.dot(B,E))
print("This shows Multiplicative Identity property, where it is shown that B multiplied to E is equal to B, where E is a matrix with diagonal 1's.")
print("Since the values in the other matrix is only ones arranged diagonally and the rest are zeros, all the values shall be the same.")

[[150  18   8  35]
 [ 36 144 180 256]
 [ 24 162 200 350]
 [ 21 512 700 100]]
[[150  18   8  35]
 [ 36 144 180 256]
 [ 24 162 200 350]
 [ 21 512 700 100]]
This shows Associative property, where A*(B*C) = (A*B)*C.
----------------------------------------------------------
[[123  78  59 152]
 [ 78 120 100 146]
 [ 59 100  84 116]
 [152 146 116 238]]
[[ 79 112 107  63]
 [112 170 155 102]
 [107 155 177 137]
 [ 63 102 137 139]]
This shows Commutative property, where C*D is shown to be not equal to D*C.
----------------------------------------------------------
[[ 55  90  24   6]
 [  8  52  96  96]
 [  7  36  65  84]
 [ 70 128 200  45]]
[[ 55  90  24   6]
 [  8  52  96  96]
 [  7  36  65  84]
 [ 70 128 200  45]]
This shows Distributive property, where we can see that A*(B + C) = (A*B) + (A*C).
----------------------------------------------------------
A =  [[ 5  9  4  1]
 [ 2  4  6  8]
 [ 1  3  5  7]
 [ 7  8 10  5]]
E =  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
E multiplied to A is:
[[0 0 