<a href="https://colab.research.google.com/github/AlexaMarieDonato/58013-LinearAlgebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix Algebra

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
A = np.array([[1,4],[0,3]])
np.linalg.det(A)
B = np.array([[1,3,5,6],[0,3,1,3],[3,1,8,2],[5,2,6,8]])
np.linalg.det(B)

-235.0000000000002

In [64]:
#Coding Activity 9
import numpy as np
#Associative
A = np.array([
[5,9,4,1],
[2,4,6,8],
[1,3,5,7],
[7,8,10,5]])
B = np.array([
[6,1,2,5],
[2,9,10,4],
[6,9,8,5],
[3,8,10,4]])
C = np.array([
[5,2,1,7],
[9,4,3,8],
[4,6,5,10],
[1,8,7,5]])
print((A*B)*C)
print(A*(B*C))
print("This shows Associative property.")
#Commutative
C = np.array([
[5,9,4,1],
[2,4,6,8],
[1,3,5,7],
[7,8,10,5]])
D = np.array([
[5,2,1,7],
[9,4,3,8],
[4,6,5,10],
[1,8,7,5]])
print(np.dot(C,D))
print(np.dot(D,C))
print("This shows Commutative property.")
#Distributive
print(A*(B+C))
print((A*B)+(A*C))
print("This shows Distributive property.")
#Multiplication of zero
E = ([[0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0]])
print(A)
print(E)
print("E multiplied to A is:")
print(E*A)
print("This shows Multiplication of zero property.")
#Dimension
D = np.array([
[5,2],
[9,4],
[4,6],
[1,8]])
C = np.array([
[5,9,4,1],
[2,4,6,8]])
print(np.dot(D,C))
print("This shows Dimension property, where since the dimensions are 4 by 2 and 2 by 4, the dimensions of the product is 4 by 4.")
#multiplicative Identity
E = ([
[1,0,0,0],
[0,1,0,0],
[0,0,1,0],
[0,0,0,1]])
B = np.array([
[6,1,2,5],
[2,9,10,4],
[6,9,8,5],
[3,8,10,4]])
print(np.dot(B,E))
print("This shows Multiplicative Identity property, where it is shown that A multiplied to E is equal to A because E is a matrix with diagonal 1's.")

[[150  18   8  35]
 [ 36 144 180 256]
 [ 24 162 200 350]
 [ 21 512 700 100]]
[[150  18   8  35]
 [ 36 144 180 256]
 [ 24 162 200 350]
 [ 21 512 700 100]]
This shows Associative property.
[[123  78  59 152]
 [ 78 120 100 146]
 [ 59 100  84 116]
 [152 146 116 238]]
[[ 79 112 107  63]
 [112 170 155 102]
 [107 155 177 137]
 [ 63 102 137 139]]
This shows Commutative property.
[[ 55  90  24   6]
 [  8  52  96  96]
 [  7  36  65  84]
 [ 70 128 200  45]]
[[ 55  90  24   6]
 [  8  52  96  96]
 [  7  36  65  84]
 [ 70 128 200  45]]
This shows Distributive property.
[[ 5  9  4  1]
 [ 2  4  6  8]
 [ 1  3  5  7]
 [ 7  8 10  5]]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
E multiplied to A is:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
This shows Multiplication of zero property.
[[29 53 32 21]
 [53 97 60 41]
 [32 60 52 52]
 [21 41 52 65]]
This shows Dimension property, where since the dimensions are 4 by 2 and 2 by 4, the dimensions of the product is 4 by 4.
[[ 6  1  2  5]
 [ 2  9 10 