<a href="https://colab.research.google.com/github/AlexaMarieDonato/58013-LinearAlgebra/blob/main/Python_Exercise_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Operations and Its Applications

In [7]:
import numpy as np
A = np.array([[-0.4],[4.3],[-0.6]])
B = np.array([-0.2, 0.2, 1])
C = np.array([-0.2, 2.1, 1.5])
D = A + B + C
E = A - B - C
F = A * B * C
G = A / B / C
print("When we add the three vectors, we get:\n", D)
print("When we subtract the three vectors, we get:\n", E)
print("When we multiply the three vectors, we get:\n", F)
print("When we divide the three vectors, we get:\n", G)

When we add the three vectors, we get:
 [[-0.8  1.9  2.1]
 [ 3.9  6.6  6.8]
 [-1.   1.7  1.9]]
When we subtract the three vectors, we get:
 [[ 0.  -2.7 -2.9]
 [ 4.7  2.   1.8]
 [-0.2 -2.9 -3.1]]
When we multiply the three vectors, we get:
 [[-0.016 -0.168 -0.6  ]
 [ 0.172  1.806  6.45 ]
 [-0.024 -0.252 -0.9  ]]
When we divide the three vectors, we get:
 [[-10.          -0.95238095  -0.26666667]
 [107.5         10.23809524   2.86666667]
 [-15.          -1.42857143  -0.4       ]]
