<a href="https://colab.research.google.com/github/AlexaMarieDonato/58013-LinearAlgebra/blob/main/Vector_Spaces_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix in Array

In [1]:
import numpy as np
A = np.array([4, 3])
B = np.array([2, -5])

print("Vector A is ", A)
print("Vector B is ", B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


Making a row vector to a column vector

In [13]:
import numpy as np
ball1 = np.array([[1], [2], [3]])
print(ball1)

[[1]
 [2]
 [3]]


Shape of the Matrix

In [26]:
import numpy as np
ball1 = np.array([1, 2, 3])
ball2 = np.array([0, 1, -1])
print(ball1)
print(ball2)
b1 = np.shape([ball1, ball2])
print(b1)

[1 2 3]
[ 0  1 -1]
(2, 3)


Vector Addition and Subtraction

In [38]:
import numpy as np

a = np.array([4, 3])
b = np.array([2, -5])
R = a + b
r = np.add(a,b)
S = a - b
s = np.subtract(a,b)
sub = np.subtract(b,a)
print(R)
print(r)
print(S)
print(s)
print(sub)

[ 6 -2]
[ 6 -2]
[2 8]
[2 8]
[-2 -8]


Vector Multiplication

In [43]:
import numpy as np
#scalar product
A = np.array([4, 3])
S = 5*A
print(S)

B = np.array([2])
s = B*A
print(s)

[20 15]
[8 6]


In [60]:
import numpy as np
#Let's code this
#Cross Product of A and B
A = np.array([2, 3])
B = np.array([1, 7])
output = np.cross(A, B)
output1 = np.dot(A, B)
print(output)
print(output1)

C = np.array([4, 3])
D = np.array([[2],[-5]])
output2 = np.dot(C, D)
print(output2)

11
23
[-7]


Properties of Matrix

In [69]:
#Identity Matrix
c = np.eye(2,2)
print(c)
d = np.eye(3,3)
print(d)

#Zero Matrix
e = np.zeros([5,5])
print(e)

#Full Matrix
f = np.full([4, 4], 7)
print(f)

#Transpose Matrix
F =  np.array([[2, 5], [3, 6]])
g = np.transpose(F)
print(g)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[2 3]
 [5 6]]
